parameters:
  windowsPool: Hosted Windows 2019 with VS2019

jobs:
- job: Windows
  pool: ${{ parameters.windowsPool }}
  steps:
  - template: clear-packagecaches.yml
  - template: install-dependencies.yml

  - powershell: |
      dotnet tool install --tool-path $(Agent.TempDirectory) nbgv --ignore-failed-sources
      $(Agent.TempDirectory)/nbgv cloud
    displayName: Set build number

  - ${{ if eq(variables['system.collectionId'], '011b8bdf-6d56-4f87-be0d-0092136884d9') }}:
    - template: microbuild.before.yml

  - template: dotnet.yml

  - ${{ if eq(variables['system.collectionId'], '011b8bdf-6d56-4f87-be0d-0092136884d9') }}:
    - template: microbuild.after.yml

  - template: expand-template.yml

- job: Linux
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - template: install-dependencies.yml
  - template: dotnet.yml
  - template: expand-template.yml

- job: macOS
  pool:
    vmImage: macOS 10.13
  steps:
  - template: install-dependencies.yml
  - template: dotnet.yml
  - template: expand-template.yml

- job: WrapUp
  dependsOn:
  - Windows
  - Linux
  - macOS
  pool:
    vmImage: Ubuntu 16.04
  condition: succeededOrFailed()
  steps:
  - template: install-dependencies.yml
  - template: publish-codecoverage.yml
  - template: publish-deployables.yml
