steps:

- task: CredScan@3
  displayName: Run CredScan

- task: PoliCheck@2
  displayName: Run PoliCheck
  inputs:
    targetType: F
    targetArgument: $(System.DefaultWorkingDirectory)
    optionsUEPATH: $(System.DefaultWorkingDirectory)\azure-pipelines\PoliCheckExclusions.xml

- task: PostAnalysis@2
  displayName: Break on compliance issues
  inputs:
    GdnBreakAllTools: true
    GdnBreakGdnToolBinSkimSeverity: Warning
